// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Model.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkUnits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkUnits));
        
        string IMigrationMetadata.Id
        {
            get { return "201508110125028_WorkUnits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
